spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: fooduser
    password: ${POSTGRESS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hotel-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.hotelbooking.common.event
            value:
              default:
                type: com.hotelbooking.common.event.BookingEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
server:
  port: 8082





